[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#424242"
font = "sans serif"

# Additional settings
# Disable showing warning about pyplot global use
# This is handled by the runtime now